perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "it_IT.UTF-8",
	LC_ADDRESS = "it_IT.UTF-8",
	LC_MONETARY = "it_IT.UTF-8",
	LC_NUMERIC = "it_IT.UTF-8",
	LC_TELEPHONE = "it_IT.UTF-8",
	LC_IDENTIFICATION = "it_IT.UTF-8",
	LC_MEASUREMENT = "it_IT.UTF-8",
	LC_TIME = "it_IT.UTF-8",
	LC_NAME = "it_IT.UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
2018-04-18 00:27:48,723 - SensorNodeFactory.create_nodes_auto() - INFO - skipping unknown node type
2018-04-18 00:27:48,725 - SensorNodeFactory.create_nodes_auto() - INFO - cc2538-bsl.py  -p /dev/ttyUSB1 -a 0x00202000
Opening port /dev/ttyUSB1, baud 500000 address 0x202000
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:10:03:54:32
2018-04-18 00:27:49,186 - SensorNodeFactory.create_nodes_auto() - INFO - b''
2018-04-18 00:27:49,187 - SensorNodeFactory.create_nodes_auto() - INFO - Found Zoul on /dev/ttyUSB1
2018-04-18 00:27:51,779 - CoAPWrapper.2.__init__() - INFO - sudo ../../agent_modules/contiki/communication_wrappers/bin/tunslip6 -C -B 115200 -s /dev/ttyUSB1 fd00:c:2::1/64
<wishful_module_gitar.lib_arm_cortex_m.Zoul object at 0x73714830>
2018-04-18 00:27:52,883 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 inet `hostname` mtu 1500 up
2018-04-18 00:27:52,913 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 add fd00:c:2::1/64
2018-04-18 00:27:52,926 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 add fe80::c:2:0:1/64
2018-04-18 00:27:52,936 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0
2018-04-18 00:27:52,937 - Thread-1   - CoAPWrapper.2 - INFO - 
2018-04-18 00:27:52,945 - Thread-1   - CoAPWrapper.2 - INFO - tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
2018-04-18 00:27:52,947 - Thread-1   - CoAPWrapper.2 - INFO - inet addr:127.0.0.1  P-t-P:127.0.0.1  Mask:255.255.255.255
2018-04-18 00:27:52,948 - Thread-1   - CoAPWrapper.2 - INFO - inet6 addr: fe80::c:2:0:1/64 Scope:Link
2018-04-18 00:27:52,949 - Thread-1   - CoAPWrapper.2 - INFO - inet6 addr: fd00:c:2::1/64 Scope:Global
2018-04-18 00:27:52,950 - Thread-1   - CoAPWrapper.2 - INFO - UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
2018-04-18 00:27:52,950 - Thread-1   - CoAPWrapper.2 - INFO - RX packets:0 errors:0 dropped:0 overruns:0 frame:0
2018-04-18 00:27:52,951 - Thread-1   - CoAPWrapper.2 - INFO - TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
2018-04-18 00:27:52,952 - Thread-1   - CoAPWrapper.2 - INFO - collisions:0 txqueuelen:500
2018-04-18 00:27:52,953 - Thread-1   - CoAPWrapper.2 - INFO - RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
2018-04-18 00:27:52,954 - Thread-1   - CoAPWrapper.2 - INFO - 
2018-04-18 00:27:53,541 - Thread-1   - CoAPWrapper.2 - INFO - Got configuration message of type C
2018-04-18 00:27:53,543 - Thread-1   - CoAPWrapper.2 - INFO - Setting prefix fd00:c:2::
2018-04-18 00:27:53,544 - Thread-1   - CoAPWrapper.2 - INFO - Removing wishful_control_address: fd00:c::2
2018-04-18 00:27:53,546 - Thread-1   - CoAPWrapper.2 - INFO - New wishful_control_address: fd00:c:2::2
2018-04-18 00:27:54,526 - Thread-1   - CoAPWrapper.2 - INFO - Control prefix set and apps started
<Task pending coro=<coap_event_server() running at /export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py:106>>
2018-04-18 00:28:05,541 - Thread-3   - pyre_discovery_module.main - INFO - Discovered Controller DL-tcp://10.1.1.1:8990, UL-tcp://10.1.1.1:8989
2018-04-18 00:28:07,542 - Thread-3   - pyre_discovery_module.main - INFO - Discovered Controller DL-tcp://10.1.1.1:8990, UL-tcp://10.1.1.1:8989
2018-04-18 00:28:32,260 - Thread-1   - CoAPWrapper.2 - INFO - PEEE 5
local monitor cp started - Name: ecoap_local_monitoring_program_cocoa_cc, Id: 1 - STARTED
2018-04-18 00:29:20,927 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-18 00:29:22,975 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-18 00:29:25,032 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-18 00:29:27,093 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-18 00:29:29,148 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-18 00:29:30,154 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-18 00:29:31,160 - local_control_program - Contiki Base Connector - INFO - Attr capacity not found
2018-04-18 00:29:31,162 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-18 00:29:31,163 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-18 00:29:31,164 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-18 00:29:31,165 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_success not found
2018-04-18 00:29:31,166 - local_control_program - Contiki Base Connector - INFO - Attr IEEE802154_measurement_macStats not found
2018-04-18 00:29:31,167 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-18 00:29:31,168 - local_control_program - Contiki Base Connector - INFO - Attr coap_rto not found
2018-04-18 00:29:32,175 - local_control_program - Contiki Base Connector - INFO - Attr app_stats not found
2018-04-18 00:29:32,176 - local_control_program - Contiki Base Connector - INFO - Attr capacity not found
2018-04-18 00:29:32,177 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-18 00:29:32,178 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-18 00:29:32,179 - local_control_program - Contiki Base Connector - INFO - Attr rpl_preferred_parent not found
2018-04-18 00:29:32,180 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-18 00:29:32,181 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_success not found
2018-04-18 00:29:32,182 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-18 00:29:32,182 - local_control_program - Contiki Base Connector - INFO - Attr ipv6_stats not found
2018-04-18 00:29:32,183 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-18 00:29:32,184 - local_control_program - Contiki Base Connector - INFO - Attr coap_rto not found
2018-04-18 00:29:36,754 - Thread-1   - CoAPWrapper.2 - INFO - UDP client process startup initiated!
2018-04-18 00:29:36,758 - Thread-1   - CoAPWrapper.2 - INFO - UDP client process started!
2018-04-18 00:30:54,322 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 288
2018-04-18 00:31:18,330 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 384
2018-04-18 00:31:18,587 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 385
2018-04-18 00:31:41,587 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 477
2018-04-18 00:31:41,837 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 478
2018-04-18 00:31:42,087 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 479
2018-04-18 00:31:42,338 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 480
2018-04-18 00:32:11,340 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 596
2018-04-18 00:32:11,901 - Thread-1   - CoAPWrapper.2 - INFO - OVERFLOW COAP: TRANS OVER
2018-04-18 00:32:14,529 - Dummy-662  - coap - INFO - Response not recognized - sending RST.
2018-04-18 00:32:31,559 - Dummy-239  - coap - INFO - Response not recognized - sending RST.
2018-04-18 00:32:32,312 - Dummy-249  - coap - INFO - Response not recognized - sending RST.
2018-04-18 00:33:44,968 - Dummy-671  - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 25, in set_net_parameter
    return node.set_parameters(param_list, param_key_values_dict)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 196, in set_parameters
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-18 00:33:47,556 - Dummy-662  - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 25, in set_net_parameter
    return node.set_parameters(param_list, param_key_values_dict)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 196, in set_parameters
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-18 00:34:04,634 - Dummy-239  - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-18 00:34:05,390 - Dummy-249  - coap.requester - INFO - Request timed out
2018-04-18 00:35:04,673 - Dummy-239  - coap - INFO - Response not recognized - sending RST.
2018-04-18 00:36:37,749 - Dummy-239  - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-18 00:37:06,844 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1778
2018-04-18 00:37:07,094 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1779
2018-04-18 00:37:07,344 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1780
2018-04-18 00:37:07,594 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1781
2018-04-18 00:37:07,843 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1782
2018-04-18 00:37:29,594 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1869
2018-04-18 00:37:29,844 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1870
2018-04-18 00:37:30,094 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1871
2018-04-18 00:37:30,344 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1872
2018-04-18 00:37:30,593 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1873
2018-04-18 00:37:35,848 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1894
2018-04-18 00:37:36,094 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1895
2018-04-18 00:37:36,344 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1896
2018-04-18 00:37:36,593 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1897
2018-04-18 00:37:36,843 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 1898
2018-04-18 00:37:37,798 - Dummy-239  - coap - INFO - Response not recognized - sending RST.
2018-04-18 00:38:36,098 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 2135
2018-04-18 00:38:36,351 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 2136
2018-04-18 00:38:36,601 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 2137
2018-04-18 00:38:36,851 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 2138
2018-04-18 00:38:37,106 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 2139
2018-04-18 00:39:10,876 - Dummy-239  - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-18 00:40:10,934 - Dummy-239  - coap - INFO - Response not recognized - sending RST.
2018-04-18 00:41:44,004 - Dummy-239  - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-18 00:42:22,108 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3039
2018-04-18 00:42:22,358 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3040
2018-04-18 00:42:22,608 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3041
2018-04-18 00:42:22,861 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3042
2018-04-18 00:42:23,108 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3043
2018-04-18 00:42:23,360 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3044
2018-04-18 00:42:23,611 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3045
2018-04-18 00:42:23,857 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3046
2018-04-18 00:42:24,109 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3047
2018-04-18 00:42:24,360 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3048
2018-04-18 00:42:24,608 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3049
2018-04-18 00:42:24,858 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3050
2018-04-18 00:42:25,108 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3051
2018-04-18 00:42:25,357 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3052
2018-04-18 00:42:25,611 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3053
2018-04-18 00:42:25,859 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3054
2018-04-18 00:42:26,110 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3055
2018-04-18 00:42:26,362 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3056
2018-04-18 00:42:26,610 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3057
2018-04-18 00:42:26,858 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3058
2018-04-18 00:42:27,111 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3059
2018-04-18 00:42:27,357 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3060
2018-04-18 00:42:27,610 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3061
2018-04-18 00:42:44,062 - Dummy-239  - coap - INFO - Response not recognized - sending RST.
2018-04-18 00:44:17,079 - Dummy-239  - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 267, in read_measurements
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-18 00:44:59,123 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3667
2018-04-18 00:44:59,373 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3668
2018-04-18 00:44:59,622 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3669
2018-04-18 00:44:59,872 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3670
2018-04-18 00:45:00,122 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3671
2018-04-18 00:45:12,623 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3721
2018-04-18 00:45:12,877 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3722
2018-04-18 00:45:13,122 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3723
2018-04-18 00:45:13,372 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3724
2018-04-18 00:45:13,624 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 3725
2018-04-18 00:45:17,128 - Dummy-239  - coap - INFO - Response not recognized - sending RST.
bash: line 1:  5581 Terminated              python agent.py --config ecoap_external_advanced/ecoap_agent.yaml
